# Generated by Django 3.0.5 on 2020-04-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='cookies_id',
            field=models.CharField(default='X', max_length=50),
        ),
    ]
