# Generated by Django 3.0.5 on 2020-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200425_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookies',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookies',
            name='click_upgrades_bought',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cookies',
            name='curret_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookies',
            name='stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cookies',
            name='stage_passed',
            field=models.IntegerField(default=1),
        ),
    ]
