# Generated by Django 3.0.5 on 2020-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200425_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookies',
            name='var_o',
            field=models.IntegerField(default=-1),
        ),
    ]
