# Generated by Django 3.0.5 on 2020-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200425_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='click_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='click_upgrades_bought',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='current_gold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='stage',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='stage_passed',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='var_o',
            field=models.FloatField(default=-1),
        ),
    ]
