# Generated by Django 3.0.5 on 2020-04-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='UserUnits',
        ),
    ]
