# Generated by Django 3.0.5 on 2020-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200426_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userunits',
            name='unit_type',
            field=models.CharField(default='X', max_length=50),
        ),
    ]
