# Generated by Django 3.0.5 on 2020-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userunits_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userunits',
            name='unit_type',
            field=models.CharField(default='X', max_length=50, unique=True),
        ),
    ]
