# Generated by Django 3.0.5 on 2020-04-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200426_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(default='X', max_length=50)),
                ('skill_cost', models.FloatField(default=0)),
                ('skill_count', models.FloatField(default=0)),
                ('cookies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cookies')),
            ],
        ),
    ]
