# Generated by Django 3.0.5 on 2020-05-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200504_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookies',
            name='max_mana',
            field=models.FloatField(default=100),
        ),
    ]
