# Generated by Django 3.0.5 on 2020-04-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_cost', models.IntegerField(default=0)),
                ('unit_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Islands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_name', models.CharField(max_length=50)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='database.Units')),
                ('units', models.ManyToManyField(to='database.Units')),
            ],
        ),
    ]
