# Generated by Django 3.0.5 on 2020-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='unit_id',
            field=models.CharField(default='army<built-in function id>_<django.db.models.fields.CharField>', max_length=50),
        ),
    ]
