# Generated by Django 3.0.5 on 2020-04-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_units_unit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_name', models.CharField(max_length=50)),
                ('mob_default_hp', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='units',
            old_name='unit_cost',
            new_name='unit_default_cost',
        ),
        migrations.AlterField(
            model_name='islands',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='database.Mobs'),
        ),
        migrations.AlterField(
            model_name='islands',
            name='units',
            field=models.ManyToManyField(to='database.Mobs'),
        ),
    ]
