# Generated by Django 3.0.5 on 2020-04-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200419_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_id',
            field=models.CharField(default='xyz', max_length=50),
        ),
    ]
