# Generated by Django 3.0.5 on 2020-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200419_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_id',
            field=models.IntegerField(default=0),
        ),
    ]
