# Generated by Django 3.0.5 on 2020-04-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200419_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='islands',
            name='mob_image',
            field=models.ImageField(default=None, upload_to='islands/'),
        ),
        migrations.AddField(
            model_name='mobs',
            name='mob_image',
            field=models.ImageField(default=None, upload_to='mobs/'),
        ),
    ]
