# Generated by Django 3.0.5 on 2020-04-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_islands_ends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='islands',
            old_name='mob_image',
            new_name='island_image',
        ),
    ]
